language: python
python:
  - "3.6"
  - "3.7"

sudo: false

cache: pip

install: pip install -U . -r dev-requirements.txt

script:
  - pylint hesperidescli
  - black hesperidescli/ tests/
  - pytest

after_success: coveralls

notifications:
  email:
    on_success: never
